/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.Person_History;
import model.Person;
/**
 *
 * @author Raunak Singh Matharu
 */
public class HM_Main_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Person_History person_List;
    
    
    public HM_Main_JFrame() {
        initComponents();
        person_List = new Person_History();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel_Hospital_Main = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txt_Admin_Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txt_Admin_Password = new javax.swing.JPasswordField();
        Btn_System_Admin_Login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Role_Combo_Box = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        Panel_Hospital_Main.setBackground(new java.awt.Color(255, 51, 51));
        Panel_Hospital_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Welcome To Hospital Management System ");
        Panel_Hospital_Main.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 565, 59));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please Select Your Role ");
        Panel_Hospital_Main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 71, 458, 39));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("User Name");
        Panel_Hospital_Main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 158, 70, -1));

        Txt_Admin_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Admin_UsernameActionPerformed(evt);
            }
        });
        Txt_Admin_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Admin_UsernameKeyPressed(evt);
            }
        });
        Panel_Hospital_Main.add(Txt_Admin_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 155, 160, -1));

        jLabel3.setText("Password");
        Panel_Hospital_Main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 201, 78, -1));

        Txt_Admin_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Admin_PasswordActionPerformed(evt);
            }
        });
        Panel_Hospital_Main.add(Txt_Admin_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 160, -1));

        Btn_System_Admin_Login.setText("Login");
        Btn_System_Admin_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_System_Admin_LoginActionPerformed(evt);
            }
        });
        Panel_Hospital_Main.add(Btn_System_Admin_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("                          For Staff");
        Panel_Hospital_Main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 352, 54));

        Role_Combo_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select Your Role", "System Admin", "Doctor", "Community Admin", "Hospital Admin", " " }));
        Role_Combo_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Role_Combo_BoxActionPerformed(evt);
            }
        });
        Panel_Hospital_Main.add(Role_Combo_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 160, -1));

        jLabel6.setText("Role");
        Panel_Hospital_Main.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 236, 70, 20));

        jLabel7.setText("For Patient");
        Panel_Hospital_Main.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jButton1.setText("Patient");
        Panel_Hospital_Main.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jPanel1.add(Panel_Hospital_Main, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_Admin_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Admin_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Admin_UsernameActionPerformed

    private void Txt_Admin_UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Admin_UsernameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Admin_UsernameKeyPressed

    private void Txt_Admin_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Admin_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Admin_PasswordActionPerformed

    private void Btn_System_Admin_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_System_Admin_LoginActionPerformed
        // TODO add your handling code here:
        String x =Txt_Admin_Username.getText();
        String y =Txt_Admin_Password.getText();
        String z =Role_Combo_Box.getSelectedItem().toString();
        if(x.equalsIgnoreCase("Admin")&&y.equalsIgnoreCase("12345")&&z.equalsIgnoreCase("System Admin"))
        {
            System_Admin pd =new System_Admin();
            pd.setVisible(true);
        }
        else if(x.equalsIgnoreCase("Doctor")&&y.equalsIgnoreCase("12345")&&z.equalsIgnoreCase("Doctor")){
            Patient_Directory pd =new Patient_Directory();
            pd.setVisible(true);
        }
        
        else if(x.equalsIgnoreCase("Hospital")&&y.equalsIgnoreCase("12345")&&z.equalsIgnoreCase("Hospital Admin")){
            Patient_Directory pd =new Patient_Directory();
            pd.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "login unsucessfull");
        }
    }//GEN-LAST:event_Btn_System_Admin_LoginActionPerformed

    private void Role_Combo_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Role_Combo_BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Role_Combo_BoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HM_Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HM_Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HM_Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HM_Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HM_Main_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_System_Admin_Login;
    private javax.swing.JPanel Panel_Hospital_Main;
    private javax.swing.JComboBox<String> Role_Combo_Box;
    private javax.swing.JPasswordField Txt_Admin_Password;
    private javax.swing.JTextField Txt_Admin_Username;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
